fab-spec/fab

packages/fab-compile/package.json
packages/fab-compile/src/Compiler.ts
packages/fab-nextjs/README.md
packages/fab-nextjs/package.json
packages/fab-nextjs/src/Builder.ts
packages/fab-nextjs/src/files/mock-express-response/index.js
packages/fab-nextjs/src/files/server.js
packages/fab-nextjs/src/generateIncludes.ts
yarn.lock

Used the fact that NextJS 8's serverless outputs are _so_ similar to drastically reduce the compiled server.js size.
Bumped @fab/compile and @fab/nextjs

Upgraded @fab/nextjs to combine severless outputs

---

packages/fab-compile/src/files/fab-entry.js

Rollback @fab/compile version to the previous minor release. This changed how files not within the `_assets` directory were handled:
* In both cases, files like `/build/xyz.js` were renamed & moved to `/_assets/_public/build/xyz.a1b2c3d4.js`
* Previously, the FAB _proxied_ these requests, so the URL that the browser sees was still `/build/xyz.js`
* This was changed due to AWS Lambda@Edge limiting responses to 1mb, so the FAB would return a `302 Redirect` to the real asset path (which bypassed the FAB at the CDN level). But that caused issues in some cases (there'll be a config settings/knowledge base article about this in future).
In this case, the old behaviour prevented `@fab/serve` from serving a FAB with redirects inside a Codesandbox.
---
This is the first PR where we can observe …

Restore previous @fab/compile asset returning behaviour

---

docs/package.json
docs/yarn.lock
doczrc.js
package.json
yarn.lock

There are 3 possible ways I can think of to solve the issue :
1. That's the one in this PR: moving docz to the root of the repo.
2. Moving the docs folder inside packages so it can share node_modules with the rest of fab packages.
3. Leaving the docs folder setup as it is and configuring webpack to look for dependencies in both /node_modules and /docs/node_modules.
I went with 1 because it seemed like the easiest one.
Do you have any preference ?
> Related to #42

Fix docz v2

---

packages/input-nextjs/src/preflightChecks.ts

(copied from the other PR)
According to https://nextjs.org/docs/api-reference/next.config.js/introduction next.config.js can export a function that takes a phase and an object and returns a config.
I added a check that will run the function if that is what is returned from the next.config.js

Add function check for next-config

---

packages/cli/src/actions/Compiler.ts
packages/server/src/sandboxes/node-vm.ts

With `iife`, it is not possible to `require` a FAB in a regular Node environment. With an UMD build we have both `iife`, `CommonJS` and a global namespace to work with.

Change output format to UMD, so a FAB can be required in a Node env

---

docs/guides/contributing.mdx
docs/kb/plugin-runtime.mdx
docs/wip/new-assets.md
packages/cli/src/runtime/index.ts
packages/core/src/types.ts
packages/rewire-assets/src/runtime.ts
packages/sandbox-node-vm/src/index.ts
packages/server/package.json
packages/server/src/index.ts
tests/e2e/create-react-app.test.ts
tests/e2e/helpers/index.ts
tests/e2e/nextjs-9.test.ts
tests/e2e/paths-exist.test.ts
tests/e2e/static.test.ts
tests/e2e/workspace/.gitignore
tests/tsconfig.json
tests/utils.ts
yarn.lock

Implementing the new Request/Response returning API for `fab serve`.
This is the first big breaking change for the FAB runtime, but since we're still in pre-release for all the FAB stuff this will be just another v0 point release for the moment, until we're sure it doesn't need to be broken again.

Asset proxying

---

packages/cli/src/actions/Initializer.ts

Now when you try `fab init` without `-y`, it doesn't explode!
Also, if it doesn't detect a CRA or NextJS app it _does its best_, which is all any of us can do!

[fab init] Prompting & static fallback

---

README.md
lerna.json
package.json
packages/cli/README.md
packages/cli/package.json
packages/cli/src/actions/Generator.ts
packages/cli/src/actions/Initializer/constants.ts
packages/cli/src/actions/Initializer/index.ts
packages/core/package.json
packages/deployer-aws-lambda/package.json
packages/deployer-aws-s3/package.json
packages/deployer-cf-workers/package.json
packages/input-nextjs/package.json
packages/input-static/package.json
packages/rewire-assets/package.json
packages/rewire-assets/src/build.ts
packages/rewire-assets/test/build.test.ts
packages/sandbox-node-vm/package.json
packages/serve-html/package.json
packages/serve-html/src/build.ts
packages/serve-html/src/injections/env.ts
packages/serve-html/src/runtime.ts
packages/serve-html/src/types.ts
packages/serve-html/test/build.test.ts
packages/server/package.json
tests/e2e/create-react-app.test.ts
tests/e2e/nextjs.test.ts
yarn.lock

Right now, `fab init` only auto-detects the `public` directory if a gatsby build has been run, which is ok, but has implications for Linc.
Bigger problem is large gatsby sites. So looking at fixing https://github.com/fab-spec/fab/issues/77 as part of this.
Also, Gatsby paths break on https://github.com/reactjs/reactjs.org so we gotta fix that first.

Gatsby compatibility

---

README.md
packages/actions/src/Deployer.ts
packages/actions/src/Packager.ts
packages/cli/bin/run
packages/cli/package.json
packages/cli/src/Initializer/constants.ts
packages/cli/src/Initializer/index.ts
packages/cli/src/commands/serve.ts
packages/cli/src/helpers/index.ts
packages/cli/src/helpers/modules.ts
packages/deployer-aws-lambda/src/aws.ts
packages/deployer-aws-lambda/src/createPackage.ts
packages/deployer-aws-s3/src/index.ts
packages/deployer-cf-workers/src/createPackage.ts
packages/deployer-cf-workers/src/deploy.ts
packages/input-nextjs/src/build.ts
packages/input-nextjs/src/runtime.ts
packages/plugin-render-html/src/build.ts
packages/plugin-rewire-assets/src/build.ts
packages/plugin-rewire-assets/src/runtime.ts
packages/server/src/index.ts
yarn.lock

Didn't like how much code I was shipping with `npx fab init`, cause previously I didn't want `fab serve` to just explode without having installed `@fab/server`. Setting this up to load this on demand, and also do the same with deploy config. Should be good!

On demand installation

---

.github/workflows/public-consumer.yml
lerna.json
packages/_fab/README.md
packages/_fab/package.json
packages/actions/package.json
packages/actions/src/Deployer.ts
packages/cli/README.md
packages/cli/package.json
packages/cli/src/Initializer/constants.ts
packages/cli/src/commands/deploy.ts
packages/cli/src/commands/serve.ts
packages/cli/src/helpers/modules.ts
packages/core/package.json
packages/core/src/types.ts
packages/deployer-aws-lambda/package.json
packages/deployer-aws-s3/package.json
packages/deployer-cf-workers/package.json
packages/input-nextjs/package.json
packages/input-static/package.json
packages/plugin-render-html/package.json
packages/plugin-rewire-assets/package.json
packages/sandbox-node-vm/package.json
packages/server/package.json
tests/e2e/create-react-app.test.ts
tests/e2e/nextjs.test.ts

For CI, prompting the user to approve installing the required plugins is no good, so let's skip it (but still actually use that code to install it, rather than installing it ourselves)

Auto install flag

---

lerna.json
packages/_fab/README.md
packages/_fab/package.json
packages/actions/package.json
packages/actions/src/runtime/index.ts
packages/cli/README.md
packages/cli/package.json
packages/core/package.json
packages/core/src/helpers.ts
packages/deployer-aws-lambda/package.json
packages/deployer-aws-s3/package.json
packages/deployer-cf-workers/package.json
packages/deployer-cf-workers/templates/index.js
packages/input-nextjs/package.json
packages/input-static/package.json
packages/plugin-render-html/package.json
packages/plugin-rewire-assets/package.json
packages/sandbox-node-vm/package.json
packages/sandbox-node-vm/src/index.ts
packages/server/package.json
packages/server/src/index.ts
tests/e2e/fixtures/server-side-logic/fab-plugins/slowly.ts
tests/e2e/fixtures/server-side-logic/fab.config.json5
tests/e2e/server-side-logic.test.ts
tests/package.json
tests/utils.ts
tests/yarn.lock
yarn.lock

Why respond fast when you can respond... slowly:
```ts
import { FABRuntime } from '@fab/core'
const sleep = (ms: number) => new Promise((res) => setTimeout(res, ms))
export default ({ Router }: FABRuntime) => {
Router.on('/slowly', async () => {
const stream = new ReadableStream({
async start(controller) {
controller.enqueue('Des\n')
await sleep(500)
controller.enqueue('pa\n')
await sleep(500)
controller.enqueue('cito.\n')
controller.close()
},
})
return new Response(stream, {
headers: {
'Content-Type': 'text/plain',
},
})
})
}
```
Seriously though, streaming HTTP responses is a big part of the future of FABs and the web. Not all FAB hosts will support them (looking at you, AWS Lambda), and the above API is just a proof of concept, but useful enough to test E2E that streaming works! And …

Streaming HTTP responses

---

packages/input-nextjs/src/preflightChecks.ts
tests/e2e/nextjs.test.ts

Noticed that some of the e2e tests said CRA but were for next also added a link to documentation in the error message of the preflight check

Update test names in e2e tests

---

docs/fab.config.json5
docs/package.json
packages/core/src/constants.ts
packages/deployer-aws-s3/src/aws.ts
packages/deployer-aws-s3/src/index.ts

Add `endpoint` as a config for S3 uploads. Allows deploying to different regions with:
```json5
'aws-s3': {
access_key: '@S3_ACCESS_KEY',
secret_key: '@S3_SECRET_KEY',
region: 'us-west-1',
bucket_name: 'fab-ci-assets-fab-dev-manual-deploy-west',
endpoint: 'https://s3.us-west-1.amazonaws.com',
},
```
The `endpoint` isn't required here, region should do it, but this a) does work, and b) allows people to push static assets to any S3-compatible API like https://wasabi.com/

S3 endpoints

---

packages/cli/package.json
packages/cli/src/commands/build.ts
packages/cli/src/commands/serve.ts
packages/cli/src/errors/index.ts
packages/cli/src/helpers/index.ts
packages/cli/src/helpers/watcher.ts
packages/core/src/types.ts
packages/input-nextjs/src/build.ts
packages/plugin-render-html/src/build.ts
packages/plugin-render-html/src/runtime.ts
packages/server/src/index.ts
yarn.lock

Added `fab build --watch [dir]` and `fab serve --watch`:
This is the first step towards improving the DX of writing FAB plugins. Basically, I'm doing this:
```
fab build --watch output_dir --watch current-plugin.js
```
That'll just set up a `chokidar` loop and restart the whole `fab build` process when any file you mention changes. It's not super smart, so if a file ends up in the node require cache it won't get reloaded, but it _does_ work for plugins, `fab.config.json5` and any input directory. And it's actually pretty quick!
```
fab serve --watch
```
First up, if you forget to add `fab.zip` it now assumes that's what you meant. But now it just watches `fab.zip` and re-extracts it without having to restart the server. It works pretty well, but in future I'd like to expand this and …

Watch mode

---

packages/actions/src/runtime/index.ts
packages/input-nextjs/src/runtime.ts
packages/plugin-render-html/src/runtime.ts
packages/plugin-rewire-assets/src/runtime.ts
tests/e2e/fixtures/server-side-logic/fab-plugins/hello-world.ts
tests/e2e/fixtures/server-side-logic/fab.config.json5
tests/e2e/fixtures/server-side-logic/public/alternative.html
tests/e2e/server-side-logic.test.ts

A way of adding an early middleware to use more than the one fallback file (i.e. most routes render `/index.html` but `/alt/xyz` renders `/alternative.html`).
The syntax to do this looks like this:
```js
Router.on(
'/alt(/.*)?',
async ({ url, request }) => {
return {
replaceRequest: new Request(`${url.origin}/alternative.html`, request),
}
},
Priority.FIRST
)
```
Added a test for it, and a test to make sure that the dodgy way (mutating the `url` object) doesn't work.

Testing `replaceRequest` directive

---

docs/content/en/guides/adding-server-side-logic.md

The FAB specification allows the return of a Request to proxy that, which may allow FAB hosting platform to better optimise those. So it is preferred to return a Request than to return the fetch of that Request if you don't need to change the response in any way.

Improve docs to return a new Request rather than a fetch for proxying

---

package.json
yarn.lock

Weird test failures, not... sure how it got merged without passing the tests too...

Revert "Bump node-fetch from 2.6.0 to 2.6.1"

---

.github/workflows/public-consumer.yml
packages/input-nextjs/package.json
packages/plugin-rewire-assets/package.json
packages/plugin-rewire-assets/src/runtime.ts
tests/e2e/nextjs.test.ts

Right now we have two tests on CI, one that uses the locally-built packages, and one that uses whatever's on `npm` under the `latest` tag. The public packages one only runs on master, which means sometimes stuff breaks outside of a PR flow.
I'm thinking I might use this branch as a prerelease (hence the name) when new package versions are going to break the tests, so I can keep `master` green a bit more often...
For now though, just trying to fix this one test in front of me.

Testing: fixing the public packages test

---

packages/input-nextjs/shims/mock-express-response/index.js

Trying to render a NextJS app with `getServerSideProps` will yield the
following error:
```
ERROR: NextJS renderer crashed
TypeError: t.hasHeader is not a function
```
See https://github.com/fab-spec/fab/issues/220 and https://github.com/serverless-nextjs/serverless-next.js/pull/342#issuecomment-609999944
How about tests for this? I could only find e2e tests, is that the preferred way here?

Add `MockExpressResponse.hasHeader` (Express) shim

---

packages/sandbox-node-vm/src/index.ts
packages/server/package.json
packages/server/src/index.ts
tests/e2e/create-react-app.test.ts
tests/e2e/server-side-logic.test.ts
yarn.lock

Following on from #241, I've got an E2E test failing now, with the following message:
`curl -I localhost:3000/bigfile.a1b2c3d4e5.immutable`
```
ERROR
TypeError: stream.getReader is not a function
at Object.start (evalmachine.<anonymous>:11310:43)
at Call (/home/glen/src/projects/fab/node_modules/web-streams-polyfill/src/lib/helpers.ts:62:35)
at InvokeOrNoop (/home/glen/src/projects/fab/node_modules/web-streams-polyfill/src/lib/helpers.ts:121:10)
at startAlgorithm (/home/glen/src/projects/fab/node_modules/web-streams-polyfill/src/lib/readable-stream/default-controller.ts:342:12)
at SetUpReadableStreamDefaultController (/home/glen/src/projects/fab/node_modules/web-streams-polyfill/src/lib/readable-stream/default-controller.ts:316:23)
at …
```

E2E Testing chunking assets

---

packages/server/src/index.ts

Per [RFC 7230](https://tools.ietf.org/html/rfc7230#section-3.3.3)
If a message is received with both a Transfer-Encoding and a
Content-Length header field, the Transfer-Encoding overrides the
Content-Length.  Such a message might indicate an attempt to
perform request smuggling (Section 9.5) or response splitting
(Section 9.4) and ought to be handled as an error.  A sender MUST
remove the received Content-Length field prior to forwarding such
a message downstream.
This is to fix an error with Cypress tests wherein running the tests against a `fab serve`d site errors on assets with both a `content-length` and `transfer-encoding`

Don't set chunked transfer-encoding if content-length is set.

---

packages/cli/README.md
packages/cli/package.json
packages/cli/src/Initializer/frameworks.ts
packages/cli/src/Initializer/index.ts
packages/cli/src/Initializer/utils.ts

If you don't have `expo-cli` installed globally, this `fab init` wasn't working. Now it does.

Expo init fixes

---

docs/content/en/guides/adding-server-side-logic.md

Change `#proxying-an-api` to `#proxying-a-simple-api` to point to the correct location in the page and update its label as well to point to the correct heading.

Fix the broken reference

---

docs/content/en/kb/environment-variables.md

The config code snippet provided in the documentation on [accessing-environment-variables-at-runtime](https://fab.dev/kb/environment-variables#accessing-environment-variables-at-runtime) causes an error as `FAB_SETTINGS` is undefined:
I'm correcting the snippet so that instances of `FAB_SETTINGS` read `window.FAB_SETTINGS` instead.

Fix environment variables config snippet

---

docs/content/en/guides/deploying.md

As mentioned in Discord, I removed the part mentioning S3 as the only hosting available.

Remove mention of S3 as the only hosting available

---

packages/deployer-aws-lambda/templates/index.js

We remove a bunch of headers that are specific to the HTTP connection that make no sense to set in a FAB and are forbidden by Cloudfront as well, before returning the response to Cloudfront.
But `cache-control` was in that list as well, which means that FABs could not set *any* caching headers running in a lambda. Would be great if you could have a look why that was there @geelen. If there was a good reason to use it somewhere, that case may now stop working.

Do not remove cache-control header in Lambda wrapper

---

packages/actions/src/Deployer.ts

This enables `--env` cli option for deploy.
Fixes https://github.com/fab-spec/fab/issues/300

feat(cli): deploy env support

---

packages/actions/src/Deployer.ts

It seems like the `/kb/deploying` URL no longer exists. Update URLs from `/kb/deploying` -> `guides/deploying`

Update deploying help URLs

---

packages/input-nextjs/src/build.ts

This is a package that got added in a recent NextJS point release and breaks the build. Remains to be seen if it's used at all, so first attempt is to alias it to an empty object like the AMP stuff and see if we can get back to green.

Aliasing 'critters' to an empty object during build

---

package.json
packages/cli/package.json
packages/cli/src/Initializer/index.ts
packages/deployer-cf-workers/package.json
packages/sandbox-node-vm/package.json
packages/server/package.json
yarn.lock

Since NextJS pushes point releases all the time, and occasionally things break, adding a preflight check to suggest to user downgrading a point release:
Also added a quick note if your local `@fab/cli` is different to than what's on NPM under `latest`, since it was largely the same logic

Added a preflight check of latest/supported versions

---

docs/content/en/kb/fab-structure.md

On the site https://fab.dev/kb/fab-structure#_assets-directory there was a slight mix-up with the `_` from the `_assets` directory, causing the entire italic styling to be rendered incorrectly:

Fix italic formatting error

---

docs/content/en/kb/configuration.md

While reading through the docs of FAB, I've noticed there is a code-fence tag missing in order to properly render the docs right here https://fab.dev/kb/configuration#value-types:
This PR fixes it.

Fix missing code-fence tag

---

packages/core/src/constants.ts
packages/deployer-aws-lambda/src/aws.ts
packages/deployer-aws-lambda/src/deploy.ts
yarn.lock

Adds optional `routes_for_invalidation` to the fab config which will automatically invalidate the CloudFront cache on the specified routes. Defaults to the old value ['/'].

add option to configure CloudFront invalidation routes

---

packages/cli/package.json
packages/cli/src/Initializer/index.ts
yarn.lock

Our project is a monorepo with our nextjs app living in a yarn workspace. Running the FAB cli didn't recognize this as a yarn-using project, but this change allows it to.

When running cli init, recognize yarn workspaces as using yarn

---

packages/plugin-precompile/src/build.ts

Right now, importing TypeScript files in a plugin and using `@fab/plugin-precompile` results in the infamous:
```txt
Module not found: Error: Can't resolve './path/to/typescript/file` in `/My/plugin/directory`.
```
This lets Webpack discover those TypeScript files and hopefully successfully build, as well as `.jsx`, `.ts`, `.tsx` and `.mjs` files.

Add jsx, ts, tsx, and mjs support to @fab/plugin-precompile

---

packages/server/src/index.ts

When building the Request in the FAB Server, the Express middleware built the request with a body only for POST requests. This PR updates the `renderReq()` function to also include the body for PUT and PATCH requests.
- The approach taken is a minimal addition of string comparison using logical operators. The performance of this strategy is generally better than building arrays or Regular Expressions to compare against the string.
- An alternative approach could be to simply always pass the body. Although it is generally not used in the other methods, this solution would be syntactically correct. (see: https://tools.ietf.org/html/rfc7231#section-4.3.1)
A payload within a GET request message has no defined semantics;
sending a payload body on a GET request might cause some existing …

Updated Request Renderer to pass Body on POST, PUT, or PATCH

---

packages/deployer-aws-lambda/src/aws.ts

AWS recently released Lambda States, creators like FAB need to wait for a Lambda to be active before they can be used i.e. assigned to a cloud front distribution.
This updates the deploy code to wait for the function to be in an `Active` state before attempting to use it.
https://aws.amazon.com/blogs/compute/coming-soon-expansion-of-aws-lambda-states-to-all-functions/
https://docs.aws.amazon.com/lambda/latest/dg/functions-states.html

fix(deployer-aws-lambda): waits on lambda state to be Active before assigning to distribution
