fab-spec/fab

- packages/fab-nextjs/package.json
> Add missing dependency

- packages/fab-nextjs/src/Builder.ts
- packages/fab-nextjs/src/generateIncludes.ts
- packages/fab-nextjs/src/generateNextCache.ts
>  Support non-standard next.js output directories

- docs/package.json
- lerna.json
- package.json
- packages/cli/README.md
- packages/cli/package.json
- packages/cli/src/runtime/index.ts
- packages/core/package.json
- packages/core/src/types.ts
- packages/input-nextjs/package.json
- packages/input-static/package.json
- packages/rewire-assets/package.json
- packages/serve-html/package.json
- packages/server/README.md
- packages/server/package.json
- packages/server/src/index.ts
- packages/server/src/sandboxes/v8-isolate.ts
It won't last, but it's good for now!
> Making the v1 FABs compatible with v0 FAB runners

- package.json
- packages/cli/src/actions/Compiler.ts
- packages/cli/src/actions/Generator.ts
- packages/core/src/models/ProtoFab.ts
- packages/core/src/types.ts
- packages/input-nextjs/src/build.ts
- packages/input-static/src/build.ts
- packages/input-static/test/errors.test.ts
- packages/rewire-assets/package.json
- packages/rewire-assets/src/build.ts
- packages/rewire-assets/test/build.test.ts
- packages/serve-html/src/build.ts
- packages/serve-html/test/build.test.ts
- yarn.lock
We'd broken fonts! We've unbroken fonts!
> Binary assets handling

- packages/input-nextjs/src/build.ts
- packages/input-nextjs/src/shims/empty-object.js
- tests/e2e/fixtures/nextjs/pages/background/[size].js
- tests/e2e/fixtures/nextjs/pages/dynamic.js
> NextJS 9.2.2 support

- package.json
- packages/cli/README.md
- packages/cli/src/runtime/index.ts
- packages/core/src/types.ts
- packages/sandbox-node-vm/package.json
- packages/sandbox-node-vm/src/index.ts
- packages/serve-html/src/runtime.ts
- packages/serve-html/test/runtime.test.ts
- packages/server/package.json
- packages/server/src/index.ts
- yarn.lock
Making sure the new asset rendering works in [Linc](https://linc.sh)
> Router renderer prep

- packages/input-nextjs/src/build.ts
- packages/rewire-assets/src/build.ts
- packages/rewire-assets/src/constants.ts
- tests/e2e/create-react-app.test.ts
- tests/e2e/helpers/index.ts
- tests/e2e/nextjs.test.ts
- tests/e2e/static.test.ts
- tests/jest.config.js
Turns out I was leaving a bunch of files on the floor, oops!
This now picks up `.next/static` files and files in the `public` directory and adds tests to confirm that they're being served with the correct headers.
> Nextjs asset fixes

- docs/.gitignore
- docs/fab.config.json5
- docs/package.json
- lerna.json
- packages/cli/README.md
- packages/cli/package.json
- packages/core/package.json
- packages/deployer-aws-lambda/package.json
- packages/deployer-aws-s3/package.json
- packages/deployer-cf-workers/package.json
- packages/deployer-cf-workers/src/deploy.ts
- packages/deployer-cf-workers/src/utils.ts
- packages/input-nextjs/package.json
- packages/input-static/package.json
- packages/rewire-assets/package.json
- packages/sandbox-node-vm/package.json
- packages/serve-html/package.json
- packages/server/package.json
> [@fab/deploy-cf-workers] Routes & Zones support

- lerna.json
- package.json
- packages/cli/README.md
- packages/cli/package.json
- packages/core/package.json
- packages/deployer-aws-lambda/package.json
- packages/deployer-aws-s3/package.json
- packages/deployer-cf-workers/package.json
- packages/input-nextjs/package.json
- packages/input-static/package.json
- packages/rewire-assets/package.json
- packages/sandbox-node-vm/package.json
- packages/serve-html/package.json
- packages/server/package.json
- tests/package.json
- tests/yarn.lock
- yarn.lock
Caused by ol' nextjs inlining its dependencies, but arguably more-caused by me forgetting to explicitly specify my dependencies.
Also cleaned up the security vulnerabilities, I think.
> Path to regexp bug

- docs/guides/getting-started.mdx
Had a go at the getting started guide and I hit a few tiny tiny bumps that I thought I could help.
None of these stumped me but it was things I had to think for 2sec that you might miss.
1. `npx fab init` is good but unless you actually install it globally commands such as `fab serve` are not going to work.
The npx workflow is actually pretty good for getting started, maybe it's better to set-up package.json scripts for serve and deploy or to mention a global installation before these sections? - That's why I've not made any change here yet 
2. The `fab deploy` command was not explicit listed like the others. When I ran this I did not get the experience of "Will prompt you for your Cloudflare workers & Amazon S3 info and deploy your FAB!" - Perhaps this is the experience for other builds …
> Update some docs

- tests/e2e/fixtures/nextjs/pages/dynamic.js
- tests/e2e/nextjs.test.ts
> [@fab/input-nextjs] Use inbuilt nextjs fetch instead.

- .gitignore
- docs/fab.config.json5
- packages/actions/src/Deployer.ts
- packages/core/src/constants.ts
- packages/deployer-aws-s3/src/aws.ts
- packages/deployer-aws-s3/src/index.ts
- packages/deployer-cf-workers/package.json
- packages/deployer-cf-workers/src/deploy.ts
- packages/deployer-cf-workers/src/utils.ts
- packages/deployer-cf-workers/templates/index.js
- packages/plugin-render-html/src/runtime.ts
- packages/plugin-rewire-assets/src/constants.ts
- packages/plugin-rewire-assets/src/runtime.ts
- packages/plugin-rewire-assets/test/build.test.ts
- tests/e2e/fixtures/server-side-logic/fab-plugins/geolocate.ts
- tests/e2e/fixtures/server-side-logic/fab-plugins/slowly.ts
- yarn.lock
Proof is in the pudding, https://next.fab.dev is now rendering from the KV store!
> [@fab/deploy-cf-workers] Support KV store

- docs/content/en/plugins/introduction.md
Looks like there was a typo here, confused me for a bit!
> Fix Plugin Docs typo Markdown => Mustache

- docs/content/en/guides/contributing.md
- docs/content/en/plugins/introduction.md
Fixes at least the first part of #230 
May want to leave open to address a few others? 🤷‍♂️
> correct docs dev command, runtime routing snippet

- docs/content/en/plugins/server-side-routing.md
Fixes #217 
Feedback welcome 😃
> add initial draft of server side routing docs

- tests/e2e/fixtures/nextjs/pages/api/time.js
- tests/e2e/nextjs.test.ts
> added extremely basic e2e tests for hasHeader

- packages/server/src/index.ts
Adding some more error logging to help pinpoint the source of an error. Needs a bit more testing before it can be merged in.
> WIP - Add more error logging to @fab/serve to help debug FABs.

- packages/core/src/constants.ts
- packages/core/src/types.ts
- packages/deployer-cf-workers/src/deploy.ts
> add support for multiple routes

- .github/workflows/nodejs.yml
- .github/workflows/public-consumer.yml
- docs/README.md
- docs/content/en/guides/contributing.md
- docs/content/en/kb/environment-variables.md
- docs/wip/gatsby-theme-docz/components/Header/index.js
- docs/wip/gatsby-theme-docz/components/Layout/index.js
- packages/actions/src/Builder.ts
- packages/actions/src/Compiler.ts
- packages/plugin-precompile/test/build.test.ts
- packages/plugin-rewire-assets/test/build.test.ts
- tests/README.md
- tests/babel.config.js
- tests/e2e/cli-errors.test.ts
- tests/e2e/create-react-app.test.ts
- tests/e2e/fixtures/server-side-logic/package.json
- tests/e2e/helpers/index.ts
- tests/e2e/nextjs.test.ts
- tests/e2e/server-side-logic.test.ts
- tests/jest.config.js
- tests/jest.setup.js
- tests/package.json
- tests/utils.ts
- tests/yarn.lock
> Next tests are failing before they even get to FAB build

- packages/server/src/index.ts
Hahaha I finally found it!
I thought I'd put this `console.log` in myself and couldn't figure out where it was coming from. Turns out it was coming from inside the library.
> Remove debug line from server

- tests/e2e/server-side-logic.test.ts
> increasing threshold to 100ms for timing tests
